name: Deploy Hexo Site

on:
  push:
    branches:
      - main  # 假设你使用 master 分支进行部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # 如果你不想将 GitHub 令牌保留在构建过程中

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 指定 Node.js 的版本

    - name: Install Dependencies
      run: npm install

    - name: Deploy
      run: |
        npm install hexo-cli -g
        hexo g
      env:
        NODE_OPTIONS: --max_old_space_size=4096

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./public
