name: Deploy Hexo

on:
  push:
    branches:
      - main  # 或者你使用的是master分支，就改为master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21' # 可以根据需要选择Node.js的版本

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: |
        npm install hexo -g
        npm install
        git clone https://github.com/saicaca/hexo-theme-vivia.git themes/vivia
        npm install colorjs.io stylus hexo-symbols-count-time

    - name: Generate static pages
      run: hexo generate

    - name: Restore CNAME
        run: |
          cp -f ./CNAME_backup ./public/CNAME || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Hexo默认生成的目录
